apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
data:
  mysql-root-password: cGFzc3dvcmQ= # Base64 encoded "password"
  mysql-database: bG9naXN0aWNrcw== # Base64 encoded "logisticks"
